export const ADD_MODEL = "ADD_MODEL";
export const ADD_MODELS = "ADD_MODELS";
export const ADD_MODEL_CART = "ADD_MODEL_CART";
export const ADD_ALL_MODEL_CART = "ADD_ALL_MODEL_CART";
export const REMOVE_MODEL = "REMOVE_MODEL";
export const REMOVE_MODEL_DISABLE = "REMOVE_MODEL_DISABLE";
export const REMOVE_MODEL_CART = "REMOVE_MODEL_CART";
////////////////////////////////////////
// Agregado
export const REMOVE_USER = "REMOVE_USER";
export const EDIT_USER = "EDIT_USER";
////////////////////////////////////////
export const ORDER_MODELS_NAME_ASCENDANT = "ORDER_MODELS_NAME_ASCENDANT";
export const ORDER_MODELS_NAME_DESCENDANT = "ORDER_MODELS_NAME_DESCENDANT";
export const ORDER_MODELS_RATING = "ORDER_MODELS_RATING";
export const ORDER_MODELS_OWNED = "ORDER_MODELS_OWNED";
export const ORDER_MODELS_PRICE_ASCENDANT = "ORDER_MODELS_PRICE_ASCENDANT";
export const ORDER_MODELS_PRICE_DESCENDANT = "ORDER_MODELS_PRICE_DESCENDANT";
export const ORDER_MODELS_RELEASED = "ORDER_RELEASED";
export const FILTER_MODELS_BY_TYPES = "FILTER_BY_TYPES";
export const FILTER_MODELS_BY_COLORS = "FILTER_BY_COLORS";
export const GET_USER = "GET_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const WITH_DEPLOYMENT = "WITH_DEPLOYMENT";
export const WITHOUT_DEPLOYMENT = "WITHOUT_DEPLOYMENT";
export const CREATE_PRESETS = "CREATE_PRESETS";
export const LOGIN_TRUE = "LOGIN_TRUE";
export const DEPLOYMENT_COST = "DEPLOYMENT_COST";

// export const POST_USER = "POST_USER";
