const plantillas = [
  {
    id: 1,
    name: "name 1",
    price: 50,
    category: "minimalista",
    releasedDate: 23-09-23,
    type: "Home",
    Purchased: 3,
    color: [black, white],
    url: "https://res.cloudinary.com/dp6ojzhsc/image/upload/v1695850709/7_u3tua6.webp",
    reviews:[{rating: 2, review: "lorem ipsum"}, {rating: 4, review: "lorem ipsum"}],
  },
  {
    id: 2,
    name: "name 2",
    price: 23,
    category: "minimalista",
    releasedDate: 23-09-23,
    type: "Detail",
    Purchased: 0,
    color: [black, red],
    url: "https://res.cloudinary.com/dp6ojzhsc/image/upload/v1695850708/8_ooe46q.jpg",
    reviews:[{rating: 1, review: "lorem ipsum"}, {rating: 4, review: "lorem ipsum"}],
  },
  {
    id: 3,
    name: "name 3",
    price: 15,
    category: "base",
    releasedDate: 23-09-23,
    type: "About",
    Purchased: 3,
    color: [red, white],
    url: "https://res.cloudinary.com/dp6ojzhsc/image/upload/v1695850708/3_lhv1iq.jpg",
    reviews:[{rating: 5, review: "lorem ipsum"}, {rating: 4, review: "lorem ipsum"}],
  },
  {
    id: 4,
    name: "name 4",
    price: 70,
    category: "premium",
    releasedDate: 23-09-23,
    type: "Home",
    Purchased: 2,
    color: [green, white],
    url: "https://res.cloudinary.com/dp6ojzhsc/image/upload/v1695850709/4_hwzlco.jpg",
    reviews:[{rating: 5, review: "lorem ipsum"}, {rating: 4, review: "lorem ipsum"}],
  },
  {
    id: 5,
    name: "name 5",
    price: 60,
    category: "premium",
    releasedDate: 23-09-23,
    type: "Detail",
    Purchased: 1,
    color: [green, black],
    url: "https://res.cloudinary.com/dp6ojzhsc/image/upload/v1695850708/5_gdtnab.jpg",
    reviews:[{rating: 2, review: "lorem ipsum"}, {rating: 4, review: "lorem ipsum"}],
  },
  {
    id: 6,
    name: "name 6",
    price: 23,
    category: "minimalista",
    releasedDate: 23-09-23,
    type: "About",
    Purchased: 7,
    color: [blue, green, white],
    url: "https://res.cloudinary.com/dp6ojzhsc/image/upload/v1695850709/2_f95flf.jpg",
    reviews:[{rating: 1, review: "lorem ipsum"}, {rating: 3, review: "lorem ipsum"}],
  },
  {
    id: 7,
    name: "name 7",
    price: 40,
    category: "medium",
    releasedDate: 23-09-23,
    type: "Home",
    Purchased: 0,
    color: [black, blue],
    url: "https://res.cloudinary.com/dp6ojzhsc/image/upload/v1695850709/6_nn9jgq.jpg",
    reviews:[{rating: 3, review: "lorem ipsum"}, {rating: 4, review: "lorem ipsum"}],
  },
  {
    id: 8,
    name: "nose 8",
    price: 18,
    category: "base",
    releasedDate: 23-09-23,
    type: "Home",
    Purchased: 15,
    color: [black, white, blue],
    url: "https://res.cloudinary.com/dp6ojzhsc/image/upload/v1695850709/1_qvkdgk.jpg",
    reviews:[{rating: 5, review: "lorem ipsum"}, {rating: 4, review: "lorem ipsum"}],
  },
];

export default plantillas
